### PR TITLE
Server side encryption for S3

### PR DESCRIPTION
**Pull request by limed**
This gives us an optional parameter to allow optional encrypted uploads to S3

### CODE REVIEW

**Comment by limed** [comment]
Fixes issue #153

**Comment by tinnightcap** [comment]
r=jd

**Comment by gozer** [comment]
Hold on, this doesn't enable server-side encryption, now does it? It merely requires put operations to request encryption.

To me, at a minimum, it's not an option that's named correctly.

**Comment by limed** [comment]
Based on the docs

> the following bucket policy denies upload object (s3:PutObject) permission to everyone if the request does not include the x-amz-server-side-encryption header requesting server-side encryption.

And also

> Server-side encryption encrypts only the object data. Any object metadata is not encrypted. 

Based on the last line does that mean it is not encrypting?

**Pull request merged**
